# permissions for end users to view accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: account-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nats-accounts-operator
    app.kubernetes.io/part-of: nats-accounts-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-viewer-role
rules:
- apiGroups:
  - accounts.nats.io
  resources:
  - accounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accounts.nats.io
  resources:
  - accounts/status
  verbs:
  - get
