---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - accounts.nats.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accounts.nats.io
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - operators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accounts.nats.io
  resources:
  - operators/finalizers
  verbs:
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - operators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - signingkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accounts.nats.io
  resources:
  - signingkeys/finalizers
  verbs:
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - signingkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accounts.nats.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - accounts.nats.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
