apiVersion: accounts.nats.io/v1alpha1
kind: Account
metadata:
  name: test
  namespace: default
spec:
  seedSecretName: test-account-seed
  jwtSecretName: test-account-jwt
  limits:
    jetStream:
      memoryStorage: -1 # Unlimited
      diskStorage: 10737418240 # 10Gi
  issuer:
    ref:
      apiVersion: accounts.nats.io/v1alpha1
      kind: Operator
      name: operator
---
apiVersion: accounts.nats.io/v1alpha1
kind: User
metadata:
  name: test-user
  namespace: default
spec:
  jwtSecretName: test-user-jwt
  seedSecretName: test-user-seed
  credentialsSecretName: test-user-nats-creds
  issuer:
    ref:
      apiVersion: accounts.nats.io/v1alpha1
      kind: Account
      name: test
