# this is a Helm values file for the nats chart
config:
  resolver:
    enabled: true
    merge:
      type: full
      interval: 2m
      timeout: 1.9s
      allow_delete: true
  merge:
    operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJUS1ZVT0czSE5UVTdUWTNOVzNWWU9KNTNHQkhQQVJYSjM2QVZQNlE3UVRIN0lKS0pSNU9BIiwiaWF0IjoxNzE0MDk1OTI3LCJpc3MiOiJPQlhaWUtWNUVHV1ZCUU5RT01SS1ROQjI3RUpGUFJBQUdHN1Y0N0dIVzZNREQzVkFKSlNJVUVZTCIsIm5hbWUiOiJvcGVyYXRvciIsInN1YiI6Ik9CWFpZS1Y1RUdXVkJRTlFPTVJLVE5CMjdFSkZQUkFBR0c3VjQ3R0hXNk1ERDNWQUpKU0lVRVlMIiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0RBVVlZSllBRFBJVzNPU0ZER1JTVUFZNzRZUzRHTDc3RzJDSkZTM0hWUjY3RkdKUTNPSVBVRE0iLCJPQ082VUdTQVFZU1YzNlFQUE5WVEdYTlVLV1BLUVBDU0lCM1dESjRBNUJNR1VCMzVLTldWMlJaWSJdLCJhY2NvdW50X3NlcnZlcl91cmwiOiJuYXRzOi8vbG9jYWxob3N0OjQyMjIiLCJvcGVyYXRvcl9zZXJ2aWNlX3VybHMiOlsibmF0czovL25hdHMubmF0cy1pby5zdmMuY2x1c3Rlci5sb2NhbDo0MjIyIl0sInN5c3RlbV9hY2NvdW50IjoiQUNXT0FTWFc2NE5ZVzdQRUJNUFo3VkdKVTZQVUVJR0lISklFMlhIREhVQzVMV0dHWFZHM0tKVUYiLCJ0eXBlIjoib3BlcmF0b3IiLCJ2ZXJzaW9uIjoyfX0.cjPyfwsLg8OV78WX08yLJzurl52eubGvvbMFASEhgGnP0pYAibanpv_2uuU9DJ_GxB9xdvDlhKAvShwNOoPhCw
    system_account: ACWOASXW64NYW7PEBMPZ7VGJU6PUEIGIHJIE2XHDHUC5LWGGXVG3KJUF
