name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test
        run: make test
      - name: Build
        run: make build
# we can enable semantic release once we're happy with the 0.x.x releases and want a 1.0.0 release
#  release:
#    runs-on: ubuntu-latest
#    needs: [ build ]
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#      - name: Semantic Release
#        id: release
#        env:
#          GITHUB_TOKEN: ${{ secrets.VERSORI_BOT_PAT }}
#        uses: cycjimmy/semantic-release-action@v2
#        with:
#          semantic_version: ^18.0.0
#          extra_plugins: |
#            @semantic-release/commit-analyzer@^9.0.1
#            @semantic-release/release-notes-generator@^10.0.2
#            @semantic-release/changelog@^6.0.1
#            @semantic-release/git@^10.0.0
#            @semantic-release/github@^8.0.0
#    outputs:
#      new_release_version: ${{ steps.release.outputs.new_release_version }}
#      new_release_published: ${{ steps.release.outputs.new_release_published }}
